# Generated by Django 3.2.8 on 2021-10-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_notasaulas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notasaulas',
            options={'verbose_name': 'Notas aula', 'verbose_name_plural': 'Notas Aulas'},
        ),
    ]
